packages:
  all:
  # note the compiler and providers specifications
  # only suggest a priority order, they do not exclude other options
  # suggested priority for compilers.
    compiler: [ gcc@11.2.0, cce@15.0.0, gcc@10.3.0 ,aocc@3.2.0 ]
    providers:
      mpi: [ cray-mpich ]
      pkgconfig: [ pkg-config ]


    permissions:
      read: world
      write: user

# don't build virtuals with an external provider
  mpi:
    buildable: False
  blas:
    buildable: False
  lapack:
    buildable: False
  scalapack:
    buildable: False
  fftw-api:
    buildable: False
  
  netcdf-cxx:
    buildable: False
  netcdf-cxx4:
    buildable: False

  
  netcdf-c:
    externals:
      - spec: netcdf-c@4.9.0+mpi%gcc@11.2.0
        modules:
          - PrgEnv-gnu
          - cray-hdf5-parallel/1.12.2.1
          - cray-netcdf-hdf5parallel 
        prefix: /opt/cray/pe/netcdf-hdf5parallel/4.9.0.1/gnu/9.1
  
    buildable: False
  

  netcdf-fortran:
    externals:
      - spec: netcdf-fortran@4.5.4%gcc@11.2.0
        modules:
          - PrgEnv-gnu
          - cray-hdf5-parallel/1.12.2.1
          - cray-netcdf-hdf5parallel 
        prefix: /opt/cray/pe/netcdf-hdf5parallel/4.9.0.1/gnu/9.1

    buildable: False



  cray-mpich:
    externals:
    - spec: cray-mpich@8.1.23%gcc@11.2.0
      modules:
      - cray-mpich/8.1.23
      - craype-network-ofi
      prefix: /opt/cray/pe/mpich/8.1.23/ofi/gnu/9.1
  
  hdf5:
    externals:
      - spec: hdf5@1.12.2.1+mpi%gcc@11.2.0
        modules:
          - PrgEnv-gnu
          - cray-hdf5-parallel/1.12.2.1 
        prefix: /opt/cray/pe/hdf5-parallel/1.12.2.1/gnu/9.1/
  
    buildable: False

  pkg-config:
    externals:
    - spec: pkg-config@0.29.2
      prefix: /usr
    buildable: false
  
  libfabric:
    externals:
    - spec: libfabric@1.12.1.2.2.0.0
      modules:
      - libfabric/1.12.1.2.2.0.0
      prefix: /opt/cray/libfabric/1.11.0.4.128
    buildable: False

  
